## List of possible names for the vessels
vessel_names = ["40 Winks of Certain",
 "404",
 "80/20 (Stocks/bonds split)",
 "A Bigger Boat",
 "A Wave From it All",
 "Abigail",
 "Abominable",
 "Above the Cut",
 "Abracadabra",
 "Abraxas",
 "Absolution",
 "Admiral Benbow",
 "Adventure Capitalism",
 "Agenda to Boot",
 "Agent Flow",
 "Al Kremlin",
 "Ambition at Bay",
 "Ancient Dream",
 "Andiamo",
 "Andromeda",
 "Angel Heart",
 "Antonia Graza",
 "Appa",
 "AquaQleen",
 "Aquaholic",
 "Arkansassy",
 "Arm Candy",
 "Artego",
 "Aston Martin",
 "Atomic Donut",
 "B-Yacht'ch", # This had a ' causing an issue
 "Baba Rum",
 "Baby Moon",
 "Bacon in the Sun",
 "Bamboo Gnu",
 "Banana Cabana",
 "Barrel Roll",
 "Batteries Not Included",
 "Beat The Clock",
 "Bee Saw",
 "Beeragra",
 "Bella Rosa",
 "Belljar",
 "Big Nauti",
 "Big Top",
 "Black Pearl",
 "Black Velvet Mauve",
 "Blind Fury",
 "Bloat",
 "Blue Highways",
 "Bo Didley",
 "Boat Bums",
 "Boilcat",
 "Bonus Time",
 "Brass Monkey",
 "Brig-a-Doom",
 "Bugabug",
 "Bullship",
 "Butterfly Crush",
 "Buzz Light Year",
 "Can of Sardines",
 "Captain Runaway",
 "Captain Zipperneck",
 "Carpe Diem",
 "Casa Aqua",
 "Cash Cow",
 "Celtic Rose",
 "Cersei",
 "Champagne On Deck",
 "Chateau Yo",
 "Chips and Guac",
 "Chop Chop",
 "Chorus",
 "Chrome Dancer",
 "Cirrhosis of the River",
 "Clam Chop",
 "Cloudy With A Chance of Rain",
 "Cod Sharks",
 "Codependence",
 "Colony Clutch",
 "Comvoy",
 "Constant Plank",
 "Constant Taco",
 "Cook Bookie",
 "Cookie Monster",
 "Copabull",
 "Cordless Phoney",
 "Corrupt to the Core",
 "Cosmic Crunch",
 "Cosmic Fish",
 "Could Be Worse",
 "Cracker Jack",
 "Crassabout",
 "Crew Sin",
 "Crimea River",
 "Cruel Sea",
 "Curb Appeal",
 "Dancing in the Storm",
 "Dark Secret",
 "Dazed and Confused",
 "Deadliest Catch",
 "Deep Six",
 "Del Mar Dinghy",
 "Denture Capital",
 "Detachment",
 "Dialogue",
 "Diamantra",
 "Dirty Harry",
 "Dirty Oar",
 "Dixie Jones",
 "Dog Philosophy",
 "Dory",
 "Dragbot",
 "Dream Weaver",
 "Dredgery",
 "Due South",
 "Earthmark",
 "Ellen Ripley",
 "Endipine",
 "Enter Name Here",
 "Escapade",
 "Eternal City",
 "European Blend",
 "Exhibit A",
 "Extreme Spurts",
 "Extro",
 "Eyes Flow",
 "Fat Baby",
 "Fatbelly",
 "Feelin' Nauti",
 "Fiber Glass Eye",
 "Fight For Your Right",
 "Fin & Tonic",
 "Finsta Guana",
 "First Edition",
 "Flash Dance",
 "Fleshpot",
 "Flori-duh",
 "Flotilla the Hun",
 "Flying Dutchman",
 "Fog Blob",
 "Freedom",
 "Friendly Fire",
 "Fuelin Around",
 "Full Throttle",
 "Future Poor Person",
 "Fuzzy Prawn",
 "Georgia Girl",
 "Gestalt",
 "Gloat",
 "God Of War",
 "Golden Coin",
 "Goliath",
 "Good Luck Charm",
 "Good Vibrations",
 "Grace",
 "Grace to Glory",
 "Grand Scale",
 "Great A'Tuin",
 "Great Pumpkin",
 "Gull Oriented",
 "Hail Mary",
 "Hairplane",
 "Halcyon Arms",
 "Hands On",
 "Hard Knox",
 "Hemingway and Hawing",
 "Hidden Agenda",
 "High Coup",
 "Holly Frontier",
 "Homer Sapiens",
 "Honey Passions",
 "Hoodie",
 "Hook",
 "Horpor",
 "Horrid Crab",
 "How Are Your Sea Legs?",
 "How to Lose a Guy in 10 Days",
 "Humvegan",
 "Hunker Down",
 "Hypnotic Grace",
 "I Heard That",
 "Ice Can",
 "Iliad",
 "Image Is Everything",
 "Inducing Introducing",
 "Instigator",
 "Irish Wake",
 "Island Time",
 "Isle of Woman",
 "Jack the River",
 "Jaded",
 "Jamocha Jerky",
 "Jetsam",
 "Joe Cuzzi",
 "Journey",
 "Judge and Jury",
 "Judgment Pay",
 "Just Starting Out",
 "Killer Duck",
 "King Wasabi",
 "Kioxi",
 "Kipling",
 "Kissy Suzuki",
 "Knot On-Call",
 "Knot Paid For",
 "Knot Shore",
 "Know Boat",
 "La Belle Vita",
 "La Loopy",
 "Lady Heather",
 "Landslide",
 "Langley",
 "Lap of Luxury",
 "Lartego",
 "Lazarus",
 "Legacy",
 "Lexass",
 "Liberty",
 "Lick the Toad",
 "Life Preserver",
 "Life Support",
 "Life of Leisure",
 "Liquid Ambassador",
 "Liquid Asset",
 "Liquid Granite",
 "Liquid Skin",
 "Little Shop of Horrors",
 "Lollilo Lolo",
 "Lost Bait",
 "Lou Cid",
 "Lucifer",
 "Lucy",
 "Mad Gravity",
 "Made the Hard Way",
 "Magenta",
 "Magikarp",
 "Mangelica",
 "Marital Law",
 "Mauve Ho",
 "Metaphor Money",
 "Micro Monkey",
 "Midmorning",
 "Midnight Cowgirl",
 "Millenium Seagull",
 "Minor Key",
 "Miss Conduct",
 "Miss Kitty",
 "Miss MyMoney",
 "Misty Seas",
 "Mo Mauve",
 "Moby Debt",
 "Moby Dink",
 "Mod Pod",
 "Moisten and Remove",
 "Monkey Double",
 "Monkey Muscle",
 "Moon Milk",
 "More Than Enough",
 "Motion Sack",
 "Moxy",
 "Mr. Big and Tall",
 "Mr. Demeanor",
 "Mr. Down and Out",
 "Mr. Joshua",
 "Mr. Mercurial",
 "Mr. Ten Pin",
 "Mr. Tip-Sea",
 "Ms. Alliance",
 "Ms. Demeanor",
 "Mudlyn",
 "Murky Moments",
 "My Bad",
 "Nasdact",
 "Nastenka",
 "Nauti Buoy",
 "Nauti-Buoy",
 "Nautilus",
 "Neoprene Flotilla",
 "Neptune",
 "Neptune Reef",
 "Never Again",
 "Nifty Glob",
 "Nimboat 2000",
 "Nirvana",
 "No Convent",
 "No Regrets",
 "No Worries",
 "Northern Exposure",
 "Not So Happy",
 "Number 6",
 "Oasis",
 "Obey",
 "Ocean Suite",
 "Oceanary",
 "Octopuddle",
 "OffAndOn",
 "Oh My Hovercraft",
 "Old Fashion",
 "Old Ivy",
 "Omega Red",
 "On High",
 "On The Rocks",
 "On the Rocks",
 "One Size Fits All",
 "Orb",
 "Orion",
 "Oscillation",
 "Overbored",
 "Paradise Pirate",
 "Parent Trap",
 "Paris Taxes",
 "Pearl",
 "Pegasus",
 "Penny Foolish",
 "Penny Lotts",
 "Pentecoastal",
 "Perservance",
 "Pharoh Moans",
 "Phobia",
 "Pholio",
 "Pineapple above the Sea",
 "Pink Freud",
 "Plum Dumb",
 "Polar Storm",
 "Pomona Lisa",
 "Pornucopia",
 "Portable Torpor",
 "Poseidon",
 "Prawn Kiss",
 "Prawn Logic",
 "Prawn Phreak",
 "Prawn Queen",
 "Prawnimetric",
 "Predator",
 "Profitdom",
 "Prophet",
 "Prosperity",
 "Pura Vida",
 "Putting Zoo",
 "Quantiful",
 "Quasi-Nausea",
 "Quazonor",
 "Que",
 "Queen Sky",
 "Quest Jetter",
 "Rabid Rabbit",
 "Racing the Desert",
 "Radiant Fire",
 "Radiant Swift",
 "Random",
 "Ready for the Day",
 "Red Swan",
 "Reely Mine",
 "Resentment",
 "Rock Bottom",
 "Romeo Mauve",
 "Rooster Fuzz",
 "Roxie",
 "Royal Wetting",
 "Rudder Season",
 "Rum Runner",
 "Rumor Has It",
 "Rust Bubbles",
 "Rust Bucket",
 "Sailboat",
 "Sails Meeting",
 "Sallie Rodeo",
 "Samopolis",
 "Sand Waves",
 "Sappho",
 "Sarasonic",
 "Sea Brisket",
 "Sea Edge",
 "Sea Friar",
 "Sea Nymph",
 "Sea Quest",
 "Sea Windsor",
 "SeaMountain",
 "Seacruiser",
 "Seaduction",
 "Seas the Day",
 "Second Chance",
 "Second Wind",
 "Serendipity",
 "Serenity",
 "Serenity Now",
 "Shark Byte",
 "Sharknado",
 "Ship For Brains",
 "Ship Happens",
 "Short Squeeze",
 "Silver Surfer",
 "Simon Rusty",
 "Sin Sin",
 "Sin or Swim",
 "Sir Donna",
 "Skin Bin",
 "Slow Going",
 "Slumlord",
 "Smaug",
 "Soggy Pants",
 "Something Better",
 "Sonata Fast",
 "Southern Comfort",
 "Squeegee Spree",
 "Squid Pro Quo",
 "Star of the Quarter",
 "Stargazer",
 "Starry Ice",
 "Stella Starboard",
 "Still In Fashion",
 "Stormy Waters",
 "Storyeller",
 "Sub-lime",
 "Summer Daze",
 "Sunbright Sparrow",
 "Superstar Shippers",
 "Sushi Blue",
 "TARDIS",
 "Ta-Keel-La",
 "Tab Bandit",
 "Taboo Ways",
 "Tail Chaser",
 "Tail of the Snail",
 "Tall Goddess",
 "Tellurider",
 "Tequila Mockingbird",
 "Testimoney",
 "Texx",
 "The Belafonte",
 "The Black Pearl",
 "The Brime",
 "The Codfather",
 "The Dollop",
 "The Evil Death",
 "The Fall of the Sea",
 "The Flight",
 "The Flying Wasp",
 "The Hunger",
 "The Jones",
 "The Korla",
 "The Lollytart",
 "The Pearl",
 "The Relationshipping Department",
 "The Whole Point",
 "The Zartan",
 "Therapy",
 "This End Up",
 "Thong Thong Blue",
 "Thunder Cat",
 "ThunderSea",
 "Titanic",
 "Tooth Fury",
 "Touch Zone",
 "Tug",
 "Tuna Helper",
 "Tunapocalypse",
 "USS DEVS",
 "USS Enterprise",
 "USS Zeigler",
 "Uncle Thunder",
 "Uncorped",
 "Unfriendly Bride",
 "Unity",
 "Up To No Good",
 "Urban Sturgeon",
 "Vagabond",
 "Valium",
 "Vanilla Sky",
 "Verbal Kint",
 "Very Goodnight",
 "Viagabond",
 "Victorious Splash",
 "Vino-barbitol",
 "Vintage",
 "Volga Rarity",
 "Voodoo Vixen",
 "Voyager Templar",
 "Vvirile",
 "Waab Sandman",
 "Walkabout",
 "Wave Buster",
 "Way Cool!",
 "Weatherly",
 "Wet Lady",
 "Wet Poodle",
 "What If?",
 "Whistler",
 "White Pearl",
 "Why Not",
 "Wildcard",
 "Willy Wicket",
 "Wind Seeker",
 "Wind Song",
 "Windsor Vast",
 "Winning Ticket",
 "World Is Not Enough",
 "Xylar",
 "Yachts All Folks",
 "Yankee Dog",
 "Yeah Buoy",
 "Yield of Dreams",
 "Yo Yorkshire",
 "Yucatango",
 "Yuppie Slum",
 "Zamora",
 "Zen Rich",
 "Zenacity",
 "Zenysis",
 "Zephyr",
 "Ziggles",
 "Zilch",
 "Zilla",
 "Zilla Drop",
 "Zillaberry",
 "Zolavo",
 "Zuke"]
